// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Invitee struct {
	ID           int64          `json:"id"`
	FullName     string         `json:"full_name"`
	Email        sql.NullString `json:"email"`
	MobileNumber sql.NullString `json:"mobile_number"`
	Inviter      string         `json:"inviter"`
	StreamID     int64          `json:"stream_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Stream struct {
	ID         int64     `json:"id"`
	StreamName string    `json:"stream_name"`
	StreamLink string    `json:"stream_link"`
	Username   string    `json:"username"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
