// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateInvitee(ctx context.Context, arg CreateInviteeParams) (Invitee, error)
	CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetStream(ctx context.Context, streamName string) (Stream, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListInvitees(ctx context.Context, arg ListInviteesParams) ([]Invitee, error)
	ListStreams(ctx context.Context, arg ListStreamsParams) ([]Stream, error)
}

var _ Querier = (*Queries)(nil)
